language: node_js
node_js:
- '8'
branches:
  only:
  - master
  - develop
  - "/^v.*$/"
before_script:
- npm install
before_deploy:
- npm run prerelease
deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: S7S8dqHrG6wpKhFqcjH+BQe+PsS7mFyhQCUSBE0N5Ko0TSD+UhdPk91p+0RCwnN9kvEa6xOCp9QVIcEfiVR16vFg2iYhwkL8ZavqJT/J4DnAxnLOWq0HxB5CPyK1ZwWztJLnqRjL+oEu5fQ7QVoR94Itf9MMKblOFcPm4c24mybDw/TOIIoeMxi95MtgxnwBqwhR5XXm50lSJcKHzn1hCy/VyTcR4UO59RWKba03Tp3+uzMjWH3ZzUjuRoXOlUl1/HHBzOLBeVo7oW+5j6N6z71CMh/1IiNeVkIjwPhrr0qL8elWhFsfrYR1S8nMhA7bmd8qyLdxs8aEEZN8q4D3kaNP46ebK/+tb7LqvOWD0XCJ0gR8hAWGI9ROd1jaIyWHFsPLu4sgKnZJI7Ic4PkH8/AWpIfLSjdrhWLlSJhJfpqfzx7ukApUUgsAM7doVMbSxpuZFrNR/fqPfqDUxBCJ44CHSsCQMzkH28ovPWRDzFhhGBzGWciFwzNj36ZPX09LtpC3xiJiuIvkUcAUwFwWeqL36p+++E/x6zSb8IWsdxm/Wpy0GT8lOodzyRAsG5XR23F9/30nDiSvMAcrYpJuQ7C+YnTNJQC7QiR/b8tZoQieXbqd9dDpNXo7f95QVcriz0vqpJOGkQ0jBbiHUVRmFv3H+ivYzy+DwwZK2L4H50Y=
    file: dist.zip
    on:
      branch: master
      tags: true
      repo: flekschas/higlass-geojson
  - provider: npm
    skip_cleanup: true
    email: service@lekschas.de
    api_key:
      secure: 6N1+z9957gXaDvER9Hm8oLkDI6la12cc7kuI78dROGn3dG12YNXk2mdDPoQrkR6DMJLQlEqVM1Wu3uoBHUKh6ZG7CCy+eADazcHccIOm2qRrVCRNd1tYoz0iVk6c416GPX9nLqB8btmrUKiyG6/Lf3AhPcK/9oXBdbTdvsVCv+6wxBcBpJFobbBGfcKJPzymLWjSHfsod8pk4UmEaI2kG9Ywo5TkH3TQMkaExg/wsYPyp+FAyTtVGw6ZAlkQVnERiNOqa1a3DQTabU3PDvSsTNw3BA0e1Z/NHHHz8kOOS2ofAPUwHNzPsa3UMMdYTdLmEnMq17SBwQWDZR+4jjoSRFruDpLX4LEn+bReI367OdeqEGXWw3Nchu846fpaIUH+wjLHq/RI4idAzy+BHRja39VhsIYX5Pi/L6ffLnhP38G9gFNz/0V7VR/sVpGGxiIaXoAjfGcZn6Q7KRJy/81E0JS3V73l9ozi5tIVxpjz8fxji2qK1NaRFjJibdRV7UmOs9RbVSzOPQWACDFEmPA+kuxl0hODkaDf2lUZxYCgjcVFXIW9lko5DLKHcJ47omFCFU2Kvd699V8OgkdzeQ0/bWhzuoXKXWxsVg0zVngLcniojjZweeuMSun6/Uy9nZU4Rg7nj+4WTVJJVotfLvqYuRxwONecpLee6Untm4viS80=
    on:
      branch: master
      tags: true
      repo: flekschas/higlass-geojson
