language: node_js
node_js:
- '8'
branches:
  only:
  - master
  - develop
  - "/^v.*$/"
before_script:
- npm install
before_deploy:
- npm run prerelease
deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: S7S8dqHrG6wpKhFqcjH+BQe+PsS7mFyhQCUSBE0N5Ko0TSD+UhdPk91p+0RCwnN9kvEa6xOCp9QVIcEfiVR16vFg2iYhwkL8ZavqJT/J4DnAxnLOWq0HxB5CPyK1ZwWztJLnqRjL+oEu5fQ7QVoR94Itf9MMKblOFcPm4c24mybDw/TOIIoeMxi95MtgxnwBqwhR5XXm50lSJcKHzn1hCy/VyTcR4UO59RWKba03Tp3+uzMjWH3ZzUjuRoXOlUl1/HHBzOLBeVo7oW+5j6N6z71CMh/1IiNeVkIjwPhrr0qL8elWhFsfrYR1S8nMhA7bmd8qyLdxs8aEEZN8q4D3kaNP46ebK/+tb7LqvOWD0XCJ0gR8hAWGI9ROd1jaIyWHFsPLu4sgKnZJI7Ic4PkH8/AWpIfLSjdrhWLlSJhJfpqfzx7ukApUUgsAM7doVMbSxpuZFrNR/fqPfqDUxBCJ44CHSsCQMzkH28ovPWRDzFhhGBzGWciFwzNj36ZPX09LtpC3xiJiuIvkUcAUwFwWeqL36p+++E/x6zSb8IWsdxm/Wpy0GT8lOodzyRAsG5XR23F9/30nDiSvMAcrYpJuQ7C+YnTNJQC7QiR/b8tZoQieXbqd9dDpNXo7f95QVcriz0vqpJOGkQ0jBbiHUVRmFv3H+ivYzy+DwwZK2L4H50Y=
    file: dist.zip
    on:
      branch: master
      tags: true
      repo: flekschas/higlass-geojson
  - provider: npm
    skip_cleanup: true
    email: service@lekschas.de
    api_key:
      secure: bkCQgSvL5reu3VogLqM7ODq+lviWgiq1lSlZhQNu+aqEbdkwLAT5CMNebX8SAPg9LhFS+N+ExaK/THJm2vxaRv2Eu/7Z8y1028SkV8GFpXaajm1FI8CR1KO5pLuLrvT9ZwCXAACdyEluXqTomOBa1zQWrklwQOOvF6qwRrtEpLg4eyHK2VWeno2jhVWhuNfQJZq/6xf3D94boEhuBXmaLi/JeuGbESld8KLpZ+ndtZdLfioR1jV850jAo/MRgsO3OcTuTKpFSl3a6Au1o+AfA5ykKVIThPXG7XL5cfYzJfh21LQHlgSS5s7PmiGlK73DUw7sgjaRF4N1qeFZm++68T5zPMBbrNPabh6D6+vDJz6piecoq6FjSwCtv047Nlqo59bW4ZlzdhSituBL71AseKNiZfw+dM2TDno3szZXPNevwTYWJNVyRI8h3ii0XlMeUsteqybpVsuoKIGmoKzIyR/UbybSs8++RhvWtuOXlvqx7yTu6sk9+QSCD/McBDXjho4pIlQYynUf+ywbLMw8lQhKIJ+9nfe6qkunwPBwZqcZhJ54LPfdTTMpGyCm8R3jcs2Yb1qIr2rnARzHfN3khZ0YyT65U3q1PoeKJAm+k90If/9w4kMwOI317FxbiZE6bpdebaOaS8fmJFtaqLUTZtibKLliaQ65FvIMgokGKSo=
    on:
      branch: master
      tags: true
      repo: flekschas/higlass-geojson
